backend/controllers/SiteController.php
<?php
namespace backend\controllers;

use Yii;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;
use yii\helpers\ArrayHelper;

use common\models\Employee;
use common\models\Org;
use common\models\User;
use common\models\Login;
use common\models\SignUpForm;

class SiteController extends Controller
{

	public function behaviors() {
		return [
			'access' => ['class' => AccessControl::className(),
			'rules' => [
				[
					'actions' => [
						'signup',
						'login',
						'error'
					],
					'allow' => true,
				],
				[
					'actions' => [
						'logout',
						'index',
						'add-org',
						'update-org',
						'delete-org',
						'org',
						'down',
						'create',
						'update',
						'delete',
					],
					'allow' => true,
					'roles' => ['@'],
				],
			],
		],
	];
}

	public function actions() {
		return [
			'error' => [
				'class' => 'yii\web\ErrorAction',
			],
		];
	}

	public function actionIndex() {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Org::find()->orderBy(['date' => SORT_ASC]);
		return $this->render('index', [
			'model' => $model
		]);
	}

	public function actionOrg($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();
		$org = Org::find()->where(['id' => $id])->one();
		$model = Employee::find()->where(['org_id' => $id]);
		return $this->render('org', [
			'org' => $org,
			'model' => $model,
		]);
	}

	public function actionCreate($id) {

		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Employee();

		if (Yii::$app->request->isPost) {
			$model->name = Yii::$app->request->post()['Employee']['name'];
			$model->mail = Yii::$app->request->post()['Employee']['mail'];
			$model->phone = Yii::$app->request->post()['Employee']['phone'];
			$model->post = Yii::$app->request->post()['Employee']['post'];
			$model->org_id = $id;
			$model->date = date('Y-m-d');
			$model->save();
			return $this->redirect(['/site/org', 'id' => $id]);
		}

		return $this->render('create', [
			'model' => $model,
			'statuses' => Employee::allStatuses(),
			'orgs' => $this->getOrgs(),
		]);
	}

	public function actionUpdate($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Employee::findIdentity($id);

		if (Yii::$app->request->isPost) {
			$model->name = Yii::$app->request->post()['Employee']['name'];
			$model->mail = Yii::$app->request->post()['Employee']['mail'];
			$model->phone = Yii::$app->request->post()['Employee']['phone'];
			$model->post = Yii::$app->request->post()['Employee']['post'];
			$model->status = Yii::$app->request->post()['Employee']['status'];
			$model->save();
			return $this->redirect(['/site/org', 'id' => $model->org_id]);
		}

		return $this->render('create', [
			'model' => $model,
			'statuses' => Employee::allStatuses(),
			'orgs' => $this->getOrgs(),
		]);
	}

	public function actionDelete($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Employee::findIdentity($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionAddOrg() {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = new Org();

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Org']['title'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-org', [
			'model' => $model,
		]);
	}

	public function actionUpdateOrg($id) {
		if (Yii::$app->user->isGuest) return $this->goHome();

		$model = Org::findOne($id);

		if ($model->load(Yii::$app->request->post()) && $model->validate()) {
			$model->title = Yii::$app->request->post()['Org']['title'];
			$model->save();
			return $this->redirect(['index']);
		}

		return $this->render('add-org', [
			'model' => $model,
		]);
	}

	public function actionDeleteOrg($id) {
		if (Yii::$app->user->isGuest) {
			return $this->goHome();
		}

		$model = Org::findOne($id);
		$model->delete();
		return $this->redirect(['index']);
	}

	public function actionSignup() {

		$this->layout = 'login';

		$model = new SignUpForm();

		if(isset($_POST['SignUpForm'])) {
			$model->attributes = Yii::$app->request->post('SignUpForm');
			if($model->validate() && $model->signup()) {
				return $this->redirect(['login']);
			}
		}

		return $this->render('signup', [
			'model' => $model,
		]);
	}

	public function actionLogin() {
		if (!Yii::$app->user->isGuest) {
			return $this->goHome();
		}
		
		$this->layout = 'login';

		$model = new Login();

		if( Yii::$app->request->post('Login')) {
			$model->attributes = Yii::$app->request->post('Login');
			$user = $model->getUser();
			if($model->validate()) {
				if($user->isAdmin($user['id'])) {
					Yii::$app->user->login($user);
					return $this->goHome();
				}
			}
		}

		return $this->render('login', [
			'model' => $model,
		]);
	}

	public function actionLogout() {
		Yii::$app->user->logout();
		return $this->goHome();
	}

	public function getOrgs() {
		$orgs = [];
		$all_orgs = Org::find()->all();

		for ($i=0; $i < count($all_orgs); $i++) $orgs[$all_orgs[$i]->id] = $all_orgs[$i]->title;

		return $orgs;
	}

}

frontend/controllers/SiteController.php
<?php
namespace frontend\controllers;

use Yii;
use yii\base\InvalidParamException;
use yii\web\BadRequestHttpException;
use yii\web\Controller;
use yii\filters\VerbFilter;
use yii\filters\AccessControl;

class SiteController extends Controller {

	public function behaviors() {
		return [
		];
	}

	public function actions() {
		return [
		];
	}

	public function actionIndex() {
		return $this->redirect(['admin/']);
	}


}

backend/views/site/add-org.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Новый организация');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"></div>
		<div class="panel-body">

			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'title')->textInput() ?>

				<div class="form-group center">
					<?= Html::submitButton($model->isNewRecord ? 'Добавить' : 'Обновить', ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/create.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Новая запись');
$this->params['breadcrumbs'][] = $this->title;

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"></div>
		<div class="panel-body">

			<div class="link-update">
				<?php $form = ActiveForm::begin(); ?>

				<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
				<?= $form->field($model, 'mail')->textInput() ?>
				<?= $form->field($model, 'phone')->textInput() ?>
				<?= $form->field($model, 'post')->textInput() ?>

				<div class="form-group center">
					<?= Html::submitButton(Yii::t('app', 'Добавить'), ['class' =>  'btn btn-success']) ?>
				</div>
				<?php ActiveForm::end(); ?>
			</div>
		</div>
	</div>
</div>

backend/views/site/error.php
<?php

/* @var $this yii\web\View */
/* @var $name string */
/* @var $message string */
/* @var $exception Exception */

use yii\helpers\Html;

$this->title = $name;
?>
<div class="site-error">

    <h1><?= Html::encode($this->title) ?></h1>

    <div class="alert alert-danger">
        <?= nl2br(Html::encode($message)) ?>
    </div>

    <p>
        The above error occurred while the Web server was processing your request.
    </p>
    <p>
        Please contact us if you think this is a server error. Thank you.
    </p>

</div>

backend/views/site/index.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', 'Все организации');

$dataProvider = new ActiveDataProvider([
  'query' => $model,
  'pagination' => [
   'pageSize' => 20,
 ],
]);

?>

<?= Html::a(Yii::t('app','Добавить'), Url::base() . '/site/create') ?>

<div class="fa-br"></div>
<?php
echo GridView::widget([
  'dataProvider' => $dataProvider,
  'layout' => "{items}\n{pager}",
  'columns' => [
    'title',
    [
      'class' => 'yii\grid\ActionColumn',
      'header'=>'Действия', 
      'headerOptions' => ['width' => '80'],
      'template' => '{update} {delete}',
      'buttons' => [
        'update' => function ($url, $model) {
          return Html::a('<span class="glyphicon glyphicon-pencil"></span>', ['site/update-org', 'id'=>$model->id ], [
            'title' => Yii::t('app', 'lead-update'),
          ]);
        },
        'delete' => function ($url, $model) {
          return Html::a('<span class="glyphicon glyphicon-trash"></span>', ['site/delete-org', 'id'=>$model->id ], [
            'title' => Yii::t('app', 'lead-delete'),
          ]);
        }

      ],
    ],
  ],
]);
?>

backend/views/site/login.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Login';
$this->params['breadcrumbs'][] = $this->title;
?>
<br><br><br><br><br>
<div class="row">
	<div class="col-md-6 col-md-offset-3 ">
		<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

		<?= $form->field($model, 'email')->textInput(['autofocus' => true])
		->input('text', ['placeholder'=>'email']) ?>

		<?= $form->field($model, 'password')->passwordInput()->input('password', ['placeholder'=>'Password'])?>

		<div class="form-group">
			<?= Html::submitButton('Войти', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
			<hr>
			<?= Html::a('Регистрация', ['/site/signup'],['class' => 'btn']) ?>
		</div>
		<?php ActiveForm::end(); ?>
	</div>
</div>

backend/views/site/org.php
<?php

use yii\helpers\Html;
use yii\grid\GridView;
use yii\helpers\Url;
use yii\data\ActiveDataProvider;
use common\models\User;

$this->title = Yii::t('app', 'Работники');
$this->params['breadcrumbs'][] = $this->title;

$dataProvider = new ActiveDataProvider([
	'query' => $model,
	'pagination' => [
	 'pageSize' => 20,
	],
]);

?>
<div class="col-md-12">
	<div class="panel panel-default">
		<div class="panel-heading"><?= $this->title ?></div>
		<div class="panel-body">
			<div class="progress-group">
			</div>
			<div class="contact-index">
					<?= Html::a(Yii::t('app','Добавить работника'), ['/site/create', 'id' => $_GET['id']]) ?>
				<div class="fa-br"></div>
				<br>
				<?php
				echo GridView::widget([
					'dataProvider' => $dataProvider,
					'layout' => "{items}\n{pager}",
					'columns' => [
						'name',
						'mail',
						'phone',
						'post',
						[
							'class' => 'yii\grid\ActionColumn',
							'header'=>'Действия', 
							'headerOptions' => ['width' => '80'],
							'template' => '{update} {delete}',
						],
					],
				]);
				?>

			</div>

		</div>
	</div>
</div>

backend/views/site/signup.php
<?php

/* @var $this yii\web\View */
/* @var $form yii\bootstrap\ActiveForm */
/* @var $model \common\models\LoginForm */

use yii\helpers\Html;
use yii\bootstrap\ActiveForm;
$this->title = 'Регистрация';
$this->params['breadcrumbs'][] = $this->title;
?>
<br><br><br><br><br>
<div class="col-md-6 col-md-offset-3 ">
	<?php $form = ActiveForm::begin(['id' => 'login-form']); ?>

	<?= $form->field($model, 'username')->textInput(['autofocus' => true])->input('text', ['placeholder'=>'Логин']) ?>

	<?= $form->field($model, 'email')->textInput()->input('text', ['placeholder'=>'email']) ?>

	<?= $form->field($model, 'password')->passwordInput()->input('password', ['placeholder'=>'Пароль'])?>

	<div class="form-group">
		<?= Html::submitButton('Отправить', ['class' => 'btn btn-primary', 'name' => 'login-button']) ?>
		<hr>
		<?= Html::a('Войти', ['/site/login'],['class' => 'btn']) ?>
	</div>

	<?php ActiveForm::end(); ?>
</div>

backend/views/site/update.php
<?php

use yii\helpers\Html;
use backend\components\widgets\ActiveForm;
use yii\widgets\MaskedInput;
use dosamigos\datetimepicker\DateTimePicker;

$this->title = Yii::t('app', 'Кандидаты');

$status = '';
?>
<div class="col-md-12">
    <div class="panel panel-default">
        <div class="panel-heading"><?= $model->title ?></div>
        <div class="panel-body">

<?php



$this->title = Yii::t('app', 'Update');

$this->params['breadcrumbs'][] = ['label' => 'Записи'];
$this->params['breadcrumbs'][] = ['label' => $model->title];
?>
<div class="link-update">

	<?php $form = ActiveForm::begin(); ?>

	<?= $form->field($model, 'name')->textInput(['maxlength' => true]) ?>
	<?= $form->field($model, 'mail')->textInput() ?>
	<?= $form->field($model, 'phone')->textInput() ?>
	<?= $form->field($model, 'post')->textInput() ?>

	<div class="form-group center">
		<?= ''// Html::submitButton($model->isNewRecord ? Yii::t('app', 'Create') : Yii::t('app', 'Update'), ['class' => $model->isNewRecord ? 'btn btn-success' : 'btn btn-primary']) ?>
		<?= Html::submitButton(Yii::t('app', 'Update'), ['class' =>  'btn btn-success']) ?>
	</div>
	<?php ActiveForm::end(); ?>


</div>

        </div>
    </div>
</div>